interface SkillCard {
    title: string;
    text: string;
    cameraAngle: CameraAngle;
    image?: string;
}

type CameraAngle = {
    position: [number, number, number];
    rotation: [number, number, number];
};

// Placeholder text
const skillCards: SkillCard[] = [
    {
        title: 'API Development',
        text: 'Bla Bla Bla',
        cameraAngle: {
            position: [1, 0, 0],
            rotation: [0, 0, 0],
        },
    },
    {
        title: 'UI Design',
        text: 'Building responsive and intuitive user interfaces etc',
        cameraAngle: {
            position: [0, 0, 0],
            rotation: [0, 0, 0],
        },
        image: 'img/api.png',
    },
    {
        title: 'Automated Testing',
        text: 'Integrating automated testing into the CI/CD pipeline etc',
        cameraAngle: {
            position: [0, 0, 0],
            rotation: [0, 0, 0],
        },
        image: 'img/api.png',
    },
    {
        title: 'Documentation',
        text: 'Clear and concise documentation, autogenerated, docFX etc',
        cameraAngle: {
            position: [0, 0, 0],
            rotation: [0, 0, 0],
        },
        image: 'img/api.png',
    },
];

export default skillCards;
