interface SkillCard {
    title: string;
    text: string;
    image?: string;
}

// Placeholder text
const skillCards: SkillCard[] = [
    {
        title: 'API Development',
        text: 'Bla Bla Bla',
        image: 'img/api.png',
    },
    {
        title: 'UI Design',
        text: 'Building responsive and intuitive user interfaces etc',
        image: 'img/api.png',
    },
    {
        title: 'Automated Testing',
        text: 'Integrating automated testing into the CI/CD pipeline etc',
        image: 'img/api.png',
    },
    {
        title: 'Documentation',
        text: 'Clear and concise documentation, autogenerated, docFX etc',
        image: 'img/api.png',
    },
];

export default skillCards;
